### ISSUE TITLE
Stuck in the loading

### ISSUE THREAD

**Issue by SzKristof97** [phawitpp/SuperLandmine#2]
Sometimes the game stucks in the generating world scene and nothing happens, so i went to the console and fount the error in the following picture
![error-report](https://github.com/phawitpp/SuperLandmine/assets/47104780/f2fe427d-77b2-45e7-8439-b4831f87050c)

I checked your source code and i think i have the solution for this problem. In the next picture place a checker before you call the spawnableMapObjects[0] array, becouse it could be null and that caused the crash.
![solution](https://github.com/phawitpp/SuperLandmine/assets/47104780/e5abb2a4-a0e7-4249-a33e-40e139998513)

**Comment by phawitpp** [comment]
I've updated the new version 1.0.3
