### ISSUE TITLE
Mines Spawning Outside make the game/pc crash (MULTIPLAYER)

### ISSUE THREAD

**Issue by santocraft** [phawitpp/SuperLandmine#5]
Version 1.1.0. Making the mines spawn outside for multiplayer, makes the game not load after attempting to generate the Seed of each map and it gets stuck generating the seed, in multiple occasions the game crashed and also made the whole PC crash too.

After few tries we've discovered that the issue is the mines spawning outside ONLY IF everyone in the lobby has this specific setting turned on, however if only the Host has this setting ON, the game loads just fine for everyone, and it is correctly synced.
I hope this issue helps for future fixes.

**Comment by phawitpp** [comment]
@santocraft Do you mean that it will not crash if only host has the setting turn on, am I right?

**Comment by santocraft** [comment]
> @santocraft Do you mean that it will not crash if only host has the setting turn on, am I right?

Yes, if the host is the only one that has it turned on, it does not crash. But if other players do, the game crashes.

**Comment by phawitpp** [comment]
@santocraft I have updated the 1.1.1 version you can check it out :)))

**Comment by santocraft** [comment]
> @santocraft I have updated the 1.1.1 version you can check it out :)))

Just tested it with a friend, seems to be fine now that both of us have it turned on! You saved my PC from crashing!
