### ISSUE TITLE
whenever an enemy dies, it gives an error spam

### ISSUE THREAD

**Issue by parakatins** [phawitpp/SuperLandmine#7]
whenever an enemy dies to a mine the log keeps repeating the same error over and over

"SetDestination can only be called on an active agent that is on a NavMesh"

I don't know why it happens, but it drops the fps

**Comment by phawitpp** [comment]
I think the error that you got was enemy ai error. Sometime the fps is drop due to the stuck of enemy somewhere. Maybe you can try to use the mod name "FixCentipedeLag" to fix stuck enemy. Hope this helps. :)))

**Comment by parakatins** [comment]
> I think the error that you got was enemy ai error. Sometime the fps is drop due to the stuck of enemy somewhere. Maybe you can try to use the mod name "FixCentipedeLag" to fix stuck enemy. Hope this helps. :)))

I didn't find out what causes it, but apparently this happens when the mine explodes, but it continues "pinging" when you use the scanner, but this happens because of a conflict with some mod, I don't know which one unfortunately because I end up using a lot of mods, so the The problem itself is not SuperLandmine, sorry for the confusion

(edit#1) I was doing some testing, and it seems that mods that change the sound of the landmine cause this, because there is a delay when the mines explode to load the sound, and this makes the game kind of not recognize the explosion of the landmine, at the same time it no longer exists, this problem can occur if several landmines explode at once too (anything that causes the game to lag)
I hope this helps someone and sorry for the huge text
